# Generated by Django 2.1.2 on 2018-10-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
    ]
