# Generated by Django 2.1.2 on 2018-10-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0002_remove_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grades',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
