# Generated by Django 2.1.2 on 2018-10-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0003_auto_20181025_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='name',
        ),
        migrations.AddField(
            model_name='assignments',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignments',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grades',
            name='assignment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cop.assignments'),
            preserve_default=False,
        ),
    ]
