# Generated by Django 2.1.2 on 2018-10-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0004_auto_20181025_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
