# Generated by Django 2.1.2 on 2018-10-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0005_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classreschedules',
            name='new_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classreschedules',
            name='new_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classreschedules',
            name='old_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classreschedules',
            name='old_time',
            field=models.CharField(max_length=100),
        ),
    ]
