# Generated by Django 2.1.2 on 2018-10-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0006_auto_20181026_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preclassreq',
            name='need_day',
            field=models.CharField(max_length=100),
        ),
    ]
