# Generated by Django 2.1.2 on 2018-11-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0007_auto_20181026_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.CharField(max_length=20),
        ),
    ]
