# Generated by Django 2.1.2 on 2018-11-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0008_auto_20181110_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='feeschedules',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('studentdegree', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
            ],
        ),
    ]
