# Generated by Django 2.1.2 on 2018-11-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0009_feeschedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='studentdegree',
        ),
    ]
